### ISSUE TITLE
Add image for crypto model in assets/getCrypto request

### ISSUE THREAD

**Issue by smooth-vlad** [DeducMe/NetworthBackend#1]
![image](https://user-images.githubusercontent.com/45800516/235991031-ba43c040-ab72-4f46-aee8-e2bbfb11705b.png)

**Comment by smooth-vlad** [comment]
Currently, the assets/getCrypto API endpoint returns an array of crypto objects containing information such as the name, price, currency, and other relevant details for the requested cryptocurrencies. However, the response does not include an image (logo) for each cryptocurrency. This issue proposes adding a new property to the crypto object, called image, containing the URL of the cryptocurrency's logo.

**Comment by DeducMe** [comment]
Added "crypto" object with "thumb" and "large"
