### ISSUE TITLE
Sort Crypto Tokens in the crypto/list API Endpoint

### ISSUE THREAD

**Issue by smooth-vlad** [DeducMe/NetworthBackend#6]
Currently, the crypto/list API endpoint returns a list of crypto tokens without any specific sorting order. This issue proposes adding sorting functionality to the endpoint, allowing users to retrieve tokens in a specific order, such as by name, market cap, or other relevant criteria.

**Comment by DeducMe** [comment]
Now api/crypto/list is a "POST" request

Here is the new sorting body where 1 is ASC and -1 is DESC
{
	"sort": {
		"name": 1,    
		"marketCapRank": 1
	}
}
